name = "swim-tracker-front"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "directory"
dir = "out"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true